name: Build & deploy
on: [push, workflow_dispatch]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code 
        uses: actions/checkout@v4
      - name: Install dependense
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          path: dist
          name: dist-files
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with: 
          name: dist-files


