name: Test Vue app
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repositiry code 
        uses: actions/checkout@v4
      - name: install dependense
        run: npm ci
      - name: Test application
        run: echo testing...
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo deploying...
  