name: Print Pull request
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs: 
    print: 
        runs-on: ubuntu-latest
        steps: 
            - name: Test pull request
              run: echo "${{ toJson(github.event) }}"
